services:
  mongodb:
    image: mongo:latest
    container_name: service-gateway
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ndeyehoudiasylla02
      MONGO_INITDB_ROOT_PASSWORD: CdW3Gf7T7AztEQ0z
    ports:
      - "8085:8085"
    volumes:
      - ./database-data:/data/db

  mysqldb:
    image: mysql:lts
    command: --mysql-native-password=ON
    ports:
      - "3308:3306"
    environment:
      - MYSQL_DATABASE=users-db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=SD21048787@@
      - MYSQL_ROOT_PASSWORD=SD21048787@@
    volumes:
      - ./mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      retries: 5
      interval: 3s
      timeout: 30s
  springboot-gateway-docker:
    build: .
    ports:
      - "8080:8082"
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/users-db?serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=SD21048787@@
