#spring:
 # cloud:
  #  gateway:
   #   routes:
    #    - id : r1
     #     uri : http://localhost:8082/
      #    predicates :
       #     - Path= /patients/**
        #- id : r2
         # uri :  http://localhost:8083/
          #predicates :
           # - Path= /notes/**
    #discovery:
     # enabled: false
#server:
 # port: 8888